### PR TITLE
Codemirror fields in DC / Chart overlays

### PR DESCRIPTION
**Pull request by annatraussnig**
Screenshot 2021-01-06 at 10 15 04

(incl. linting, auto-close brackets, and auto-indent in JSON)

### CODE REVIEW

**Comment by ovbm** [comment]
Design Question. Would it be possible to make the two columns flex with a min-width for the JSON code editor and the Preview would fill the rest of the width. I think for publikator users the preview is a bit more important than the code area, which needs to have a min-width, but doesn't need to fill the rest of the space.

**Review by ovbm — COMMENTED** [review]
editor/utils/Editors.js maybe rename to editor/utils/CodeEditros.js ? So that it's not confused with the normal editor?

**Review by ovbm — APPROVED** [review]

**Comment by annatraussnig** [comment]
What do you make of `EditorFields.js`as a name? 
The column thing sound like an improvement – I'll update the screenshot for you to review once I'm done.

**Comment by ovbm** [comment]
Editorfields is ok. But if they are all related to code, then I would opt for CodeEditorFields maybe? :D

**Comment by annatraussnig** [comment]
look at us doing Java 😆

**Pull request merged**
