### PR TITLE
feat: notifySubscribers on publish

### PR DESCRIPTION
**Pull request by patte**
Screenshot from 2020-03-19 03-59-38

depends on https://github.com/orbiting/backends/pull/375

### CODE REVIEW

**Comment by tpreusse** [comment]
I've added automatic pre-selecting if a document has not been published before and always show the checkbox but with an disabled state and note:
Screenshot 2020-03-19 at 19 41 33

**Comment by tpreusse** [comment]
(and abused the branch a bit to translate the link validation feature)

**Comment by patte** [comment]
@tpreusse cool! But in that screenshot, the greyed out "Benachrichtigungen senden" should not be checked.

**Comment by tpreusse** [comment]
> @tpreusse cool! But in the state of that screenshot, the greyed out "Benachrichtigungen senden" must not be checked. Like this it looks like it's going to send it, just I can not deactivate it.

Well the idea was that you're not surprised that it will send notifications when unselecting internal (which is always preselected). Currently I'm forcing zero for count while internal is selected. Let's sleep on it.

**Comment by patte** [comment]
Yes, I think it's better that it's always there. It should just be unchecked if `internal===true`. (The BE ignores `notifySubscribers` if `prepublication===true`)

**Pull request merged**
