### PR TITLE
Chart Archiv

### PR DESCRIPTION
**Pull request by annatraussnig**
A minimal version of the chart explorer we worked towards. Idea is to start simple, obverse the behaviour of whoever use the thing, and reconvene.

Screenshot 2021-07-09 at 16 16 55

Code preview/actions for a given chart
Screenshot 2021-07-12 at 13 21 50

Simple pagination
Screenshot 2021-07-09 at 16 17 18

## TODO

- [x] use API data 
- [x] handle pagination
- [x] set links to frontend and publikator docs
- [x] radios to filter for a specific chart type
- [x] text search

### CODE REVIEW

**Comment by patrickvenetz** [comment]
Began testing and found that on staging, search term field responds poorly on key down. It seems this is because most recent charts are scatterplotts, with tons of data.

Feels to me like it's trying to rerender upon a key stroke? Do we have any means to optimize that?

https://user-images.githubusercontent.com/331800/125242618-3dfc3f00-e2ed-11eb-8f0e-e33fab342c28.mov

**Comment by annatraussnig** [comment]
Thanks for the feedback @patrickvenetz! I've change the form so that it searches/refreshes the charts on enter. Let me know :)

**Comment by patrickvenetz** [comment]
@annatraussnig Change works.

It does behave different to other search fields in Publikator – having to hit Enter – and I was wondering, if there is a way to still debounce search without hitting enter.

**Comment by annatraussnig** [comment]
Well I was debouncing before and it was laggy. Opinions @tpreusse ?

**Comment by patrickvenetz** [comment]
It felt like not deboucing was laggy, but each key stroke let to a re-render attempt.

**Comment by annatraussnig** [comment]
re-added debounce

**Comment by patrickvenetz** [comment]
@annatraussnig Works now as originally intended. 👏

**Comment by annatraussnig** [comment]
We did it 💪

**Review by patrickvenetz — APPROVED** [review]
LGTM

**Pull request merged**
